### ISSUE TITLE
02

### ISSUE THREAD

**Issue by DaviAugusto778** [jacsonrbinf/ip-2024#103]
Tive duvidas em questões de como realizar a questão de número 15, no fato de não ter conseguido achar uma maneira de decompor um número em partes de números pares.

**Comment by LeonardoCFilho** [comment]
Na questão 15 você não deve decompor o número recebido em partes de números pares, você deve encontrar, em ordem crescente, os números positivos e pares que são menores ou iguais ao valor N recebido e fazer a impressão dos dados solicitados.

Avise se eu não ter esclarecido a dúvida.
