### ISSUE TITLE
duvida sobre teste da lista 02

### ISSUE THREAD

**Issue by Coto-nete** [jacsonrbinf/ip-2024#114]
queria conferir se o output do teste 7
1 2 0 40 34 35 16 
do exercicio 5 da lista2 está correto, na linha visao 1, 2 formam um sequencia crescente de tamanho 2 mas o output esta 1

**Comment by LeonardoCFilho** [comment]
Sua confusão surgiu na diferença entre número de elementos e o comprimento da sequência, assim como informado pelo exercício, "O comprimento do segmento é dado pelo número de
elementos do segmento menos um".
Por isso que a resposta é 1, já que o número de elementos da sequência é 2.

Avise se eu não ter esclarecido a dúvida.

**Comment by Coto-nete** [comment]
certinho

**Comment by Coto-nete** [comment]
mas e os outros testes
se for considerar desse jeito o teste 1 ta com output errado
3,4,5

**Comment by LeonardoCFilho** [comment]
Para o primeiro caso de teste:
9
5 10 3 2 4 7 9 8 5
As sequências de valores crescentes são:
5 10
2 4 7 9
A sequência de maior comprimento é a segunda, com 4 elementos e comprimento igual a 3.

Para ser um pouco mais explícito, nesse exercício não há ordenação de vetores e a comparação deve ser feita entre um elemento e seu sucessor.

**Comment by Coto-nete** [comment]
ahhh 
ent n precisa ser com diferença de 1 unidade ent

**Comment by Coto-nete** [comment]
resolvido ent obg

**Comment by LeonardoCFilho** [comment]
Beleza, se tiver mais alguma dúvida só mandar um comentário aqui ou abrir uma nova issue.
