### ISSUE TITLE
ip-2024-02

### ISSUE THREAD

**Issue by lucascostalv** [jacsonrbinf/ip-2024#116]
Lucas Costa de Alvarenga
202201702
https://github.com/lucascostalv/ip-2024-02

**Comment by hvittorioguadagnini** [comment]
Boa noite, Lucas. Acredito que não seja necessário criar um novo repositório para a lista 2. Você pode só colocar a lista 2 no mesmo repositório onde a lista 1 foi colocada mesmo.
