### ISSUE TITLE
Minhas dúvidas

### ISSUE THREAD

**Issue by AnaLuisa1016** [jacsonrbinf/ip-2024#35]
Questão 15 e questão 19.

**Comment by LeonardoCFilho** [comment]
Como a pergunta foi vaga eu vou fazer uma descrição básica das questões.
Questão 15:
Você deve encontrar, em ordem crescente, os números positivos e pares que são menores ou iguais ao valor N recebido e fazer a impressão dos dados solicitados.

Questão 19:
Informar se o número 'k' recebido é válido, se for válido, imprimir o resultado do somatório de 1 + 1/2 + 1/3 + 1/4 + ... + 1/k, senão informar o usuário como descrito no exercício.

Avise se eu não ter esclarecido a dúvida.
