### ISSUE TITLE
Minhas dúvidas

### ISSUE THREAD

**Issue by V1N1C1U5ESPINDOLA** [jacsonrbinf/ip-2024#50]
O laço de repetição funciona da mesma maneira em outras linguagens ?

**Comment by LeonardoCFilho** [comment]
Comparada a outras linguagens imperativas sim.
Exemplos:
for():
for i := 0; i < 10; i++ {
    //código 
}

While():
for i < 10 { 
    //código 
}

Loop infinito:
for {
    //código
}
Note que para usar o loop infinito você precisará de inserir a condição de parada manualmente, usando um break ou algo equivalente
