### ISSUE TITLE
02

### ISSUE THREAD

**Issue by Zefelip** [jacsonrbinf/ip-2024#57]
Não consegui realizar a questão 18 pois não compreendi seu algoritmo

**Comment by LeonardoCFilho** [comment]
Em uma progressão aritmética, há uma diferença de razão R entre um elemento e seu sucessor, de modo que:
A1 é o primeiro elemento
A2 = (A1) + R
A3 = (A2) + R
Mas sabemos que A2 = A1 + R, então podemos fazer uma substituição, resultando em:
A3 = A1 + R + R
A3 = A1 + 2*R

Visto que a diferença entre elementos seguidos é sempre a mesma, podemos criar uma fórmula universal para qualquer 'n' elemento que é An = A1 + (n-1)*R.
Como demonstração:
n = 3
A3 = A1 + (3-1)*R
A3 = A1 + 2*R
É universalizado para: An = A1 + (n-1)*R

Avise se eu não ter esclarecido a dúvida.

**Comment by LeonardoCFilho** [comment]
Visto que já faz 3 dias que essa pergunta foi respondida, a issue será fechada.
Caso a dúvida ainda persista ou retorne, avise aqui ou em uma nova issue.
