### ISSUE TITLE
02

### ISSUE THREAD

**Issue by claudioferreira23** [jacsonrbinf/ip-2024#89]
Realizei as atividades mas não sei se estão corretas, gostaria de receber um feedback e a correção das atividades.

**Comment by LeonardoCFilho** [comment]
Leia um pouco melhor o que o exercício pede;
Descreva melhor como seu algoritmo funciona, muitos passos e/ou partes críticas foram pulados ou ignoradas;
Tome um pouco mais de cuidado com a lógica usada e ao digitar, alguns erros relativamente pequenos são o suficiente para o algoritmo não funcionar de maneira correta, por exemplo, um erro pequeno, mas que impede seu algoritmo de funcionar na questão 1 é a condicional incompleta do Se Media.

**Comment by LeonardoCFilho** [comment]
Visto que já faz 3 dias que essa pergunta foi respondida, a issue será fechada.
Caso a dúvida ainda persista ou retorne, avise aqui ou em uma nova issue.
