### ISSUE TITLE
02

### ISSUE THREAD

**Issue by daviddaves1** [jacsonrbinf/ip-2024#90]
Todas as atividades foram realizadas satisfatoriamente, porém, algumas podem não estar corretas.

**Comment by LeonardoCFilho** [comment]
Leia um pouco melhor os exercícios antes de fazê-los, principalmente quanto a resposta solicitada, tome um pouco mais de cuidado na lógica de suas condições, principalmente quando você faz o uso de mais de uma condição para um resultado, de resto, bom trabalho.

**Comment by LeonardoCFilho** [comment]
Visto que já faz 3 dias que essa pergunta foi respondida, a issue será fechada.
Caso a dúvida ainda persista ou retorne, avise aqui ou em uma nova issue.
